### ISSUE TITLE
Repo

### ISSUE THREAD

**Issue by unlocKing** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#24]
What's the repo so it can grab the updates correctly?

Last repo points to offshore.

**Comment by mathsgrinds** [comment]
Hi there, Offshore Git had some problems recently and are now longer providing the same service as before and recommended dev to look at other options due to excessive bandwidth usage -- so I've just (in the last few min) but the repo on my site: the link will redirect to latest repo zip: https://www.mathsgrinds.ie/repo
